// options of Expertise
export const options = [
  { label: "Account Executive" },
  { label: "Account Manager" },
  { label: "Accountant" },
  { label: "Actor/Actress" },
  { label: "Actuary" },
  { label: "Administrative Assistant" },
  { label: "Advertising Copywriter" },
  { label: "Advertising Creative Director" },
  { label: "Advertising Executive" },
  { label: "Aerospace Engineer" },
  { label: "Agile Coach" },
  { label: "Agile Product Manager" },
  { label: "AI Engineer" },
  { label: "Air Traffic Controller" },
  { label: "Aircraft Cleaner" },
  { label: "Aircraft Mechanic" },
  { label: "Airline Dispatcher" },
  { label: "Airport Administrator" },
  { label: "Airport Manager" },
  { label: "Airport Operations Supervisor" },
  { label: "Animal Shelter Caretaker" },
  { label: "Approach Controller" },
  { label: "Art Director" },
  { label: "Art Gallery Assistant" },
  { label: "Art Teacher" },
  { label: "Artist" },
  { label: "Assembly Line Worker" },
  { label: "Athlete" },
  { label: "Auditor" },
  { label: "Avionics Technician" },
  { label: "Babysitter/Nanny" },
  { label: "Back-End Developer" },
  { label: "Baggage Handler" },
  { label: "Baggage Services Agent" },
  { label: "Bank Teller" },
  { label: "Barista" },
  { label: "Bartender" },
  { label: "Branch Manager" },
  { label: "Brand Manager" },
  { label: "Branding Specialist" },
  { label: "Broadcast Technician" },
  { label: "Bus Driver" },
  { label: "Business Consultant" },
  { label: "Business Development Manager" },
  { label: "Business Intelligence Analyst" },
  { label: "Business Owner" },
  { label: "Call Centre Agent" },
  { label: "Call Centre Supervisor" },
  { label: "Camp Counsellor" },
  { label: "Carpenter" },
  { label: "Cashier" },
  { label: "Ceramic Artist" },
  { label: "Character Performer" },
  { label: "Chemical Engineer" },
  { label: "Chief Financial Officer (CFO)" },
  { label: "Choreographer" },
  { label: "Cinematographer" },
  { label: "Civil Engineer" },
  { label: "Civil Servant" },
  { label: "Cleaning Supervisor" },
  { label: "Client Relationship Manager" },
  { label: "Cloud Architect" },
  { label: "Cloud Operations Engineer" },
  { label: "Cloud Security Engineer" },
  { label: "Cloud Solutions Architect" },
  { label: "Coach" },
  { label: "Comedy Club Manager" },
  { label: "Comedy Producer" },
  { label: "Comedy Writer" },
  { label: "Communications Specialist" },
  { label: "Community Outreach Specialist" },
  { label: "Compensation and Benefits Analyst" },
  { label: "Compliance Officer" },
  { label: "Composer" },
  { label: "Computer Vision Engineer" },
  { label: "Concert Promoter" },
  { label: "Construction Labourer" },
  { label: "Content Creator" },
  { label: "Cook" },
  { label: "Copywriter" },
  { label: "Costume Designer" },
  { label: "Craftsperson" },
  { label: "Creative Director" },
  { label: "Credit Analyst" },
  { label: "Curriculum Developer" },
  { label: "Curriculum Specialist" },
  { label: "Customer Service Representative" },
  { label: "Customer Success Manager" },
  { label: "Cybersecurity Analyst" },
  { label: "Dancer" },
  { label: "Data Analyst" },
  { label: "Data Engineer" },
  { label: "Data Scientist" },
  { label: "Database Administrator" },
  { label: "Day-care Assistant" },
  { label: "Deep Learning Engineer" },
  { label: "Delivery Driver" },
  { label: "Design Director" },
  { label: "DevOps Engineer" },
  { label: "Digital Marketer" },
  { label: "Director" },
  { label: "Doctor" },
  { label: "Dog Walker" },
  { label: "Driver" },
  { label: "Duty-Free Shop Manager" },
  { label: "E-commerce Manager" },
  { label: "Editor" },
  { label: "Education Administrator" },
  { label: "Electrical Engineer" },
  { label: "Electrician" },
  { label: "Employee Relations Specialist" },
  { label: "Enroute Controller" },
  { label: "Entertainment Coordinator" },
  { label: "eSports Player" },
  { label: "Ethical Hacker" },
  { label: "Event Coordinator" },
  { label: "Event Planner" },
  { label: "Facilities Technician" },
  { label: "Fare Analyst" },
  { label: "Fashion Designer" },
  { label: "Fashion Illustrator" },
  { label: "Fashion Photographer" },
  { label: "Fashion Show Coordinator" },
  { label: "Fashion Stylist" },
  { label: "Film Director" },
  { label: "Film Editor" },
  { label: "Finance Manager" },
  { label: "Financial Advisor" },
  { label: "Financial Analyst" },
  { label: "Financial Consultant" },
  { label: "Financial Controller" },
  { label: "Flight Attendant" },
  { label: "Food Delivery Driver" },
  { label: "Freight Forwarder" },
  { label: "Front-End Developer" },
  { label: "Fuelling Technician" },
  { label: "Full Stack Developer" },
  { label: "Fundraising Manager" },
  { label: "Game Designer" },
  { label: "Game Developer" },
  { label: "Game Tester" },
  { label: "Glassblower" },
  { label: "Government Affairs Manager" },
  { label: "Graphic Designer" },
  { label: "Groomer" },
  { label: "Ground Operations Supervisor" },
  { label: "Ground Services Agent" },
  { label: "Groundskeeper" },
  { label: "Guest Services Representative" },
  { label: "Hairstylist" },
  { label: "Health Administrator" },
  { label: "Healthcare Administrator" },
  { label: "Hotel Front Desk Agent" },
  { label: "Hotel Manager" },
  { label: "Housekeeping Attendant" },
  { label: "Housekeeping Staff" },
  { label: "HR Business Partner" },
  { label: "HR Manager" },
  { label: "Human Resources Manager" },
  { label: "HVAC Technician" },
  { label: "Illustrator" },
  { label: "Improvisational Actor" },
  { label: "Information Desk Agent" },
  { label: "Information Security Engineer" },
  { label: "Interior Designer" },
  { label: "Inventory Analyst" },
  { label: "Investment Analyst" },
  { label: "Investment Banker" },
  { label: "IT Consultant" },
  { label: "IT Program Manager" },
  { label: "IT Project Manager" },
  { label: "Janitor" },
  { label: "Janitorial Staff" },
  { label: "Jewellery Designer" },
  { label: "Journalist" },
  { label: "Judge" },
  { label: "K9 Handler" },
  { label: "Kitchen Helper" },
  { label: "Lab Technician" },
  { label: "Lawyer" },
  { label: "Leatherworker" },
  { label: "Legal Assistant" },
  { label: "Legal Consultant" },
  { label: "Legal Secretary" },
  { label: "Legislative Assistant" },
  { label: "Lighting Designer" },
  { label: "Lighting Technician" },
  { label: "Literary Agent" },
  { label: "Loan Officer" },
  { label: "Logistics Coordinator" },
  { label: "Machine Learning Engineer" },
  { label: "Maid" },
  { label: "Makeup Artist" },
  { label: "Management Consultant" },
  { label: "Manufacturing Engineer" },
  { label: "Market Research Analyst" },
  { label: "Marketing Coordinator" },
  { label: "Marketing Manager" },
  { label: "Massage Therapist" },
  { label: "Mechanical Engineer" },
  { label: "Media Relations Manager" },
  { label: "Medical Researcher" },
  { label: "Medical Technologist" },
  { label: "Mehndi Designer" },
  { label: "Merchandiser" },
  { label: "Mobile App Developer" },
  { label: "Model" },
  { label: "Mortgage Specialist" },
  { label: "Music Journalist" },
  { label: "Music Producer" },
  { label: "Music Teacher" },
  { label: "Musician" },
  { label: "Nail Technician" },
  { label: "Natural Language Processing (NLP) Engineer" },
  { label: "Network Administrator" },
  { label: "Network Security Engineer" },
  { label: "News Anchor" },
  { label: "Nurse" },
  { label: "Operations Manager" },
  { label: "Painter" },
  { label: "Paralegal" },
  { label: "Performance Testing Engineer" },
  { label: "Pet Sitter" },
  { label: "Pharmacist" },
  { label: "Photographer" },
  { label: "Photojournalist" },
  { label: "Physical Therapist" },
  { label: "Physician" },
  { label: "Pilot" },
  { label: "Plumber" },
  { label: "Policy Analyst" },
  { label: "Principal" },
  { label: "Procurement Specialist" },
  { label: "Producer" },
  { label: "Product Manager" },
  { label: "Product Owner" },
  { label: "Production Assistant" },
  { label: "Production Designer" },
  { label: "Production Manager" },
  { label: "Production Supervisor" },
  { label: "Program Coordinator" },
  { label: "Props Master" },
  { label: "Public Administrator" },
  { label: "Public Relations Officer" },
  { label: "Public Relations Specialist" },
  { label: "QA Engineer" },
  { label: "Quality Analyst" },
  { label: "Quality Control Inspector" },
  { label: "R&D Manager" },
  { label: "Radar Controller" },
  { label: "Radio DJ" },
  { label: "Ramp Agent" },
  { label: "Recording Engineer" },
  { label: "Recruitment Specialist" },
  { label: "Registered Nurse" },
  { label: "Relationship Manager" },
  { label: "Reporter" },
  { label: "Research Assistant" },
  { label: "Research Scientist" },
  { label: "Reservations Agent" },
  { label: "Restaurant Chef" },
  { label: "Restaurant Server" },
  { label: "Retail Assistant" },
  { label: "Retail Sales Associate" },
  { label: "Retail Store Manager" },
  { label: "Ride Operator" },
  { label: "Risk Manager" },
  { label: "Sales Associate" },
  { label: "Sales Executive" },
  { label: "Sales Manager" },
  { label: "Sales Operations Analyst" },
  { label: "Sales Representative" },
  { label: "School Counsellor" },
  { label: "Screenwriter" },
  { label: "Scrum Master" },
  { label: "Sculptor" },
  { label: "Security Officer" },
  { label: "Security Operations Manager" },
  { label: "Security Screener" },
  { label: "Security Supervisor" },
  { label: "Set Designer" },
  { label: "Singer" },
  { label: "Social Media Coordinator" },
  { label: "Social Worker" },
  { label: "Software Engineer" },
  { label: "Sound Designer" },
  { label: "Sound Engineer" },
  { label: "Spa Attendant" },
  { label: "Stage Crew" },
  { label: "Stage Makeup Artist" },
  { label: "Stage Manager" },
  { label: "Stand-up Comedian" },
  { label: "Store Manager" },
  { label: "Strategy Analyst" },
  { label: "Streamer" },
  { label: "Studio Photographer" },
  { label: "Supply Chain Analyst" },
  { label: "Supply Chain Manager" },
  { label: "Systems Administrator" },
  { label: "Systems Analyst" },
  { label: "Talent Acquisition Specialist" },
  { label: "Talent Manager" },
  { label: "Tax Specialist" },
  { label: "Taxi/Uber Driver" },
  { label: "Teacher" },
  { label: "Technical Product Manager" },
  { label: "Technical Project Manager" },
  { label: "Technical Support Specialist" },
  { label: "Test Automation Engineer" },
  { label: "Textile Designer" },
  { label: "Ticketing Agent" },
  { label: "Tour Guide" },
  { label: "Tower Controller" },
  { label: "Training and Development Manager" },
  { label: "Travel Agent" },
  { label: "Treasury Analyst" },
  { label: "Truck Driver" },
  { label: "UI/UX Designer" },
  { label: "User Acceptance Testing (UAT) Analyst" },
  { label: "UX/UI Product Designer" },
  { label: "Veterinary Assistant" },
  { label: "Video Editor" },
  { label: "Visual Artist" },
  { label: "Volunteer Coordinator" },
  { label: "Waiter/Waitress" },
  { label: "Warehouse Manager" },
  { label: "Warehouse Supervisor" },
  { label: "Wealth Management Advisor" },
  { label: "Web Developer" },
  { label: "Wedding Planner" },
  { label: "Wildlife Photographer" },
  { label: "Woodworker" },
  { label: "Writer" },
  { label: "Youtuber" },

  // Add more options as needed
];
